
POST http://localhost:3003/user
Content-Type: application/json

{
  "name": "Paula",
  "email": "paula@dundermifflin.com",
  "password": "1235367dgj"
}

###
GET http://localhost:3003/user
Content-Type: application/json


### Delete User
DELETE http://localhost:3003/user/1674069542309
Content-Type: application/json

